### PR TITLE
Test

### PR DESCRIPTION
**Pull request by dchamorro1**
test + run_test + restriction into main
The member table restrictions and jpg in landing page

### CODE REVIEW

**Comment by aaron-sanch** [comment]
We need to have test working with the finances table properly before we can merge this.

**Review by aaron-sanch — CHANGES_REQUESTED** [review]
As mentioned in previous comment, we need to have the financeDev branch merged into test and working before we can move test into main. We don't want to push any faulty code into main.

**Review by Toadapple1 — APPROVED** [review]
Good coding standard is maintained! Tests are good to go

**Review by aaron-sanch — APPROVED** [review]

**Comment by aaron-sanch** [comment]
The appropriate changes were made, and coding standards were up to expectations. Good to go into main, as there are no issues.

**Pull request merged**
