### PR TITLE
Added Google OAuth

### PR DESCRIPTION
**Pull request by aaron-sanch**
Uses google oauth, with figaro to allow secrets to be pushed.
- Need to review how secrets are going to be added to heroku for deployment before we can deploy.
- Adds members to the member table.
- Does not yet restrict access type or page access

Followed the tutorial from https://medium.com/@amoschoo/google-oauth-for-ruby-on-rails-129ce7196f35 if there are any questions about what was done.

### CODE REVIEW

**Comment by aaron-sanch** [comment]
Has now added the restricting of access to pages using cookies and fixed bugs within login page.

**Comment by dchamorro1** [comment]
The MR follows our coding standards and successfully implements google OAuth as well as sessions. Ready to be merged to main

**Review by dchamorro1 — APPROVED** [review]
The MR follows our coding standards and successfully implements google OAuth as well as sessions. Ready to be merged to main

**Comment by capito2000** [comment]
This follows our coding standard and everything seems to be correct in regards to functionality.

**Review by capito2000 — APPROVED** [review]
This follows our coding standard and the code looks correct in regards to functionality.

**Pull request closed without merging**
