### PR TITLE
Bringing over all the functionality from test branch

### PR DESCRIPTION
**Pull request by aaron-sanch**
This is all the functionality that has been tested and approved on the test branch merging to main for final deployment.

### CODE REVIEW

**Review by Toadapple1 — APPROVED** [review]
Follows our coding standards and we have tested this before merging to main. Tested locally looks great nice job.

**Review by Toadapple1 — COMMENTED** [review]
Looks good after merge conflicts were squashed good coding standards!

**Review by Toadapple1 — APPROVED** [review]
Good job looks good after fixing merge conflict good coding standard

**Review by capito2000 — APPROVED** [review]
Everything looks good. The coding standard is followed and functionality is correct based on test branch

**Pull request merged**
